apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-cluster-kafka
  namespace: kafka
rules:
- apiGroups:
  - policy
  resourceNames:
  - my-cluster-kafka
  resources:
  - podsecuritypolicies
  verbs:
  - use
