apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-cluster-zookeeper
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-cluster-zookeeper
subjects:
- kind: ServiceAccount
  name: my-cluster-zookeeper
  namespace: kafka
