apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: strimzi-kafka-operator-app
  namespace: 25xe6
spec:
  catalog: giantswarm-playground
  config:
    configMap:
      name: 25xe6-cluster-values
      namespace: 25xe6
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: 25xe6
    inCluster: false
    secret:
      name: 25xe6-kubeconfig
      namespace: 25xe6
  name: strimzi-kafka-operator-app
  namespace: kafka
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.1.0
