apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: strimzi-kafka-operator-app
  namespace: vikq5
spec:
  catalog: giantswarm-playground-test
  config:
    configMap:
      name: vikq5-cluster-values
      namespace: vikq5
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: vikq5
    inCluster: false
    secret:
      name: vikq5-kubeconfig
      namespace: vikq5
  name: strimzi-kafka-operator-app
  namespace: kafka
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 0.0.0-dac0c60e61242be99cbb6aefec2b0012fa6a719c
